[project]
name = "job-scraper"
version = "0.1.0"
description = "SRE Job Scraper"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "playwright",
    "pandas",
    "beautifulsoup4",
    "lxml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
